//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_EntityFramework_MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_db
    {
        public int Person_ID { get; set; }
        public string Person_Name { get; set; }
        public string Person_Phone { get; set; }
        public string Person_Age { get; set; }
    }
}
